
#ifdef FEATURE_RIG_CONTROL_PASS_THROUGH
  #undef FEATURE_COMMAND_LINE_INTERFACE
#endif //FEATURE_RIG_CONTROL_PASS_THROUGH

#if defined(FEATURE_RECEIVE_FREQ_AUTOSWITCH) && !defined(FEATURE_RIG_INTERFACE)
  #error FEATURE_RECEIVE_FREQ_AUTOSWITCH requires FEATURE_RIG_INTERFACE
#endif
